### ISSUE TITLE
Add save canvas button

### ISSUE THREAD

**Issue by ExpressHermes** [ExpressHermes/Primitive-Paint#10]
Add save canvas button. Also, provide features to give margin/padding in the saved canvas.

**Comment by aksh-hash** [comment]
Sir, I can work on this,please assign it to me

**Comment by aksh-hash** [comment]
Sir, I've managed to add the save button .
please check it .
[Primitive-Paint-master.zip](https://github.com/ExpressHermes/Primitive-Paint/files/7726708/Primitive-Paint-master.zip)

**Comment by ExpressHermes** [comment]
@aksh-hash Make a PR please

**Comment by aksh-hash** [comment]
Sir, Ive figured a way out to save the image with the background color .
![myImage](https://user-images.githubusercontent.com/74498340/146664274-8bd219f5-7493-4476-94fb-bd39051a3a16.png)

**Comment by aksh-hash** [comment]
Sir, I've found a way to save the image with the background color.
![myImage](https://user-images.githubusercontent.com/74498340/146664654-1a461afe-9798-490f-a5aa-27b0c2aec869.png)

**Comment by ExpressHermes** [comment]
Resolved in #34
