### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by Khushboo288** [ExpressHermes/Primitive-Paint#17]
Your Home page needs a footer.  Please assign it to me.
I m hactoberfest Contributer.

**Comment by Khushboo288** [comment]
add Hacktoberfest 2021 label and then assign to me.

**Comment by ExpressHermes** [comment]
@Khushboo288 What do you think a good footer would be?

**Comment by luharuka** [comment]
HEY, @ExpressHermes please assign it to me. I would love to add a footer to this also add hactoberfest label

**Comment by luharuka** [comment]
HEY, @ExpressHermes please assign it to me. I would love to add a footer to this also add hactoberfest label

**Comment by ExpressHermes** [comment]
@luharuka Repeating my previous question, What do you think a good footer would be?

**Comment by ExpressHermes** [comment]
@luharuka go ahead, make a PR and in PR description post the photo of the footer please.

**Comment by ExpressHermes** [comment]
Closed in #30
