### ISSUE TITLE
Readme Updation :

### ISSUE THREAD

**Issue by ayush-sleeping** [ExpressHermes/Primitive-Paint#25]
The Readme of this Project is not well Structured , Update  the Readme of this Project.
So that any beginner, can understand this Project and get started contributing in this Repository .

**Comment by ayush-sleeping** [comment]
Hey @ExpressHermes  ,
I want to make Impressive and well Structured README for this awesome Project .
Kindly Assign me this issue under KWOC'21 .

**Comment by ExpressHermes** [comment]
Fixed in #27
