### ISSUE TITLE
Color changes in website

### ISSUE THREAD

**Issue by harshita214** [ExpressHermes/Primitive-Paint#36]
BEFORE
![nav](https://user-images.githubusercontent.com/79797000/146648341-eb0e930b-49dc-462c-a137-1c35612ca37d.png)

AFTER
![image](https://user-images.githubusercontent.com/79797000/146648378-91556aa7-f9ee-4e2a-a100-2c4793378087.png)

If it's alright can I go ahead with it

**Comment by ExpressHermes** [comment]
@harshita214 Looks good. Can you also redesign other pages(simple pen, ellipse, circle, rectangle) to follow the same color patterns?

**Comment by harshita214** [comment]
Sure!

**Comment by ExpressHermes** [comment]
@harshita214 any update on this?

**Comment by harshita214** [comment]
Yes yes, I will make a PR tomorrow. Sorry for delay

**Comment by ExpressHermes** [comment]
Fixed in #45
