### ISSUE TITLE
section under navigation bar hover problem and spacing problem in buttons

### ISSUE THREAD

**Issue by kapoor-hub** [ExpressHermes/Primitive-Paint#37]
There is a spacing problem between buttons in erase, clear screen and save. And there is also a hover problems in these buttons.

![kwoc issue](https://user-images.githubusercontent.com/83494479/146651945-54a49c0b-f071-4ef9-b36f-15d97b888339.png)

Above the arrow these 2 problems i found out i can solve it. Kindly please assign it to me.

**Comment by kapoor-hub** [comment]
Shivam Yadav @ExpressHermes kindly ,please assign this task to me.I would be heartly grateful to you!!!

**Comment by ExpressHermes** [comment]
Sorry about that. Self-assigned by mistake. Meant to assign it to you.

**Comment by ExpressHermes** [comment]
@kapoor-hub This is a very small change and can be handled in already existing issues. Hence closing this.
