### ISSUE TITLE
Eraser not working

### ISSUE THREAD

**Issue by ExpressHermes** [ExpressHermes/Primitive-Paint#46]
The eraser is not working when clicking the eraser button.

**Comment by agrajagrawal** [comment]
Hi Sir,
Please do assign me this issue!

**Comment by agrajagrawal** [comment]
Hey Fixed this in this [Pull Request](https://github.com/ExpressHermes/Primitive-Paint/pull/48)
If Possible label this contribution under Hacktoberfest2022!
Thanks :)

**Comment by ExpressHermes** [comment]
Closed in #48
